flags: {}
nix:
  enable: true
extra-package-dbs: []
ghc-options:
  ! '*': -Wall
packages:
- '.'
extra-deps:
- Histogram-0.1.0.2
- continued-fractions-0.9.1.1
- converge-0.1.0.1
- gamma-0.9.0.2
- normaldistribution-1.1.0.3
resolver: lts-8.16
