nix:
  enable: false
  packages: [zlib.dev, zlib.out]
extra-package-dbs: []
resolver: lts-11.22
packages:
- '.'
extra-deps:
- Histogram-0.1.0.2
- continued-fractions-0.9.1.1
- converge-0.1.0.1
- gamma-0.9.0.2
- normaldistribution-1.1.0.3
- gnuplot-0.5.4.2
- probability-0.2.5.1
- data-accessor-transformers-0.2.1.7
- diagrams-postscript-1.4
- diagrams-core-1.4.0.1
- diagrams-lib-1.4.2
- diagrams-solve-0.1.1
- diagrams-svg-1.4.1.1
- dual-tree-0.2.1
- lens-4.15.4
- free-4.12.4
- Chart-diagrams-1.8.3
- SVGFonts-1.6.0.3

flags: {}
